### ISSUE TITLE
Back office form must be able to connect mandates to memberships

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#201]
The form needs to be extended to allow this. Maybe not in the UI, but it should be callable from e.g. https://github.com/Project60/sepa_dd/issues/199

We might also have to include this somehow in the SepaMandate.createfull action

**Comment by magnolia61** [comment]
Would the same logic apply for adding a new action 'Record SDD Payment' to the event screen?

**Comment by systopia** [comment]
> Would the same logic apply for adding a new action 'Record SDD Payment' to the event screen?

Good point. It should.

**Comment by magnolia61** [comment]
For my understanding, would it mean that when adding a backoffice membership of event registration, it would be possible to select a payment processor (just like in the front-end) and entering the details needed for that payment processor (in our case civisepa). 
Would this need changes to civicrm core or civicrm sepa?

**Comment by systopia** [comment]
The payment processor and the back office form are two separate, parallel systems. Therefore you should be able to do this already in version 1.1 with the payment processor and an event registration page.

What we plan for version 1.2 is to make the back office form more versatile and capable of processing membership or event IDs.

**Comment by tttp** [comment]
When you use the a contribution page (or event registration) as a
backoffice user, be sure to be visiting as a new contact and not as the
admin user, otherwise you end up modifying your own contact detail instead
of creating a new one

if you want to add you own url (eg on the navigation menu) don't forget to
add &cid=0 so the fields aren't pre-filled and you are seen as an anonymous
visitor

X+

**Comment by bjendres** [comment]
This can be done using the [P60 Membership extension](https://github.com/Project60/org.project60.membership)
