### ISSUE TITLE
Recommended approach to resubmit failed payments?

### ISSUE THREAD

**Issue by cray146** [Project60/org.project60.sepa#258]
With each file submitted to the bank there are inevitably a number of failed payments. In our use case, we use SDD to collect payments for a service and we want to be able to resubmit the failed payments. What would be the recommended approach to do so? Does it suffice to look for the failed payments after the payments are marked as received, set the status again to pending and generate payments again?

Thanks

**Comment by systopia** [comment]
First of all, there is no automated procedure in place, since your workflow usually depends on the reason it failed, the purpose of the payment and the contact itself.

Now, if it's a recurring payment, and you don't terminate the mandate, the next cycle will be collected just as usual. If you want to collect the lost payment, you can simply use the "clone" button on the mandate screen to create an extra OOFF payment with the same parameters than the original RCUR payment.

If you lost a OOFF payment, you can similarly use the "clone" button to create a new one.

**Comment by cray146** [comment]
Thanks for the quick answer. I already thought about using a OOFF payment to collect lost payments but our contract with the bank only allows us to do payments under an RCUR mandate. So I was looking for a way to create a new pending contribution under the RCUR mandate to collect the lost payment. That would also avoid the overhead of creating a new mandate each time you want to collect a lost payment. Another thing is that there is no signature proving the customer agreed with the OOFF mandate. I guess this is not too much of a problem but the possibility to manually create new contribution under an existing recurring mandate seems to me more obvious.

**Comment by systopia** [comment]
Hm, that's a use case that's not supported right now. 

The contributions are created by the batching process, and that wouldn't simply generate more if one fails with the bank. Also, these new payments would violate the original terms of the mandate.

**Comment by antrik** [comment]
On Fri, Feb 27, 2015 at 07:06:11AM -0800, SYSTOPIA wrote:

> Also, these new payments would violate the original terms of the mandate.

No, they wouldn't. You just need a new pre-notification.

**Comment by systopia** [comment]
I'll close this now, please re-open if you feel that it's not adequately answered...
