### ISSUE TITLE
Notice days instead of horizon days for OOFF?

### ISSUE THREAD

**Issue by alejandro-ixiam** [Project60/org.project60.sepa#260]
Hello folks, I've been testing CiviSEPA last week and I'm not sure if this is a bug or a misunderstanding from my side about how the module works.
Seems that is taking the Notice days (and not the horizon days) for calculating contributions to be added into Groups. Is this the expected behavior or a possible bug?

Thanks!!!

**Comment by alejandro-ixiam** [comment]
Sorry... only for OOFF contributions

**Comment by systopia** [comment]
Thanks for reporting this, @alejandro-ixiam. This is a known issue and was fixed in the (about to be released) version 1.1. See: https://github.com/Project60/org.project60.sepa/commit/fdec59786450c26bca20a3bb38480134834b996c#diff-fbad2d53bb60514149459a05e7d89d2aL217

Didn't you say, though, that you observed this on ```master```?

**Comment by alejandro-ixiam** [comment]
Hi, that's great. Yes.. I noticed this using the master version. 1.0 . 

Thanks for the great work!

**Comment by systopia** [comment]
Ah, a misunderstanding then. By ```master``` I meant this repository's https://github.com/Project60/org.project60.sepa/tree/master branch, which is currently on version 1.1rc2.
