### ISSUE TITLE
Button icons broken

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#282]
With CiviCRM 4.6, all button icons seem to be broken.

**Comment by systopia** [comment]
@nikobo Could you have a look?

**Comment by magnolia61** [comment]
I do not experience problems with these on 4.6.3 and drupal 7.3.7

**Comment by systopia** [comment]
@magnolia61: could you attach a screen shot please?

**Comment by magnolia61** [comment]
![buttons_creditor](https://cloud.githubusercontent.com/assets/2195908/7912213/c2b87e5c-0865-11e5-9679-8372d2b45a34.jpg)
![buttons_dashboard](https://cloud.githubusercontent.com/assets/2195908/7912214/c2b97316-0865-11e5-8336-8e49ce892726.jpg)

**Comment by systopia** [comment]
Thanks, @magnolia61. As I suspected: the ``^`` is not supposed to be there, this used to be meaningful icons in 4.4/4.5

**Comment by systopia** [comment]
@magnolia61 Could you please confirm that the buttons are o.k. now? (current master)

**Comment by magnolia61** [comment]
The buttons did not change for me after uploading current master code. Cleaned civicrm & drupal cache + templates_c and browser cache... Anything else I can do to help test?

**Comment by systopia** [comment]
@magnolia61: Ok, that's weird. You are still on CiviCRM 4.6.3 and drupal 7.3.7, right? @nikobo: Could you imagine what happened?

**Comment by nikobo** [comment]
Hi, @magnolia61. I'm trying to fix this issue, but need more information in order to reproduce it. Could you tell me which browser (+version) you are using? @systopia It's most likely a browser-related issue, because the css class names changed between 4.4.x and 4.5. My current approach to keep everything backwards-compatible was to add both, the old and the new class names and hope for the browser to only pick the available one. It worked in my tests, but there could be some side effects.

**Comment by magnolia61** [comment]
Hi Bjorn & Nikobo, I deleted the extension fro my sever, deleted it locally, did a new git clone for the master branch, uploaded it, cleaned cache from civicrm and cleared drupal cache. After that I deleted templates_c and cleared my browser cache. Still the same buttons using drupal 7.37 and civicrm 4.6.3...

**Comment by nikobo** [comment]
@magnolia61 Could you tell me the operation system name, version and respective browser versions that you used in your tests? Thank you.

**Comment by systopia** [comment]
for all we know this is fixed.
