### ISSUE TITLE
SDD recurring payment processor doesn't send confirmation mails

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#296]
No confirmation/thank you mails are sent for *recurring* contributions, OOFF payments are fine.

To reproduce, create a contribution page with an SDD payment processor, enable recurring payments and activate confirmation mails. There's no mail sent.

**Comment by systopia** [comment]
The matter is complex. See [SE-2040](https://civicrm.stackexchange.com/questions/2040/recurring-donation-email-issues-with-iats-payment-processor), [CRM-15996](https://issues.civicrm.org/jira/browse/CRM-15996), and take a look at what the iATS-Team is doing ([IATS-79](https://github.com/iATSPayments/com.iatspayments.civicrm/issues/79) and Eileen's patch [IATS-65](https://github.com/iATSPayments/com.iatspayments.civicrm/issues/65))

**Comment by systopia** [comment]
I'll test this workaround fix for now. Once this problem is solved in the core*, we might have to remove it again.

*) To be more precise: as soon as there is a decision on how this is supposed to work. Let me know if I missed something. There's also rumors about a thorough refactoring of the whole payment processor area, which I would very much appreciate :)

**Comment by adixon** [comment]
Our solution was pretty straightforward - we just create the contributions as pending and then use the api call 'completetransaction' which can take a parameter to turn email notification on or off (it's on by default).

**Comment by systopia** [comment]
@adixon I'm not sure I can follow you. This is about recurring contributions created via the payment processor not sending out ``Contributions - Recurring Start and End Notification`` messages at the time of submission.

**Comment by adixon** [comment]
I'm probably missing some essential details about your specifics, but since you referenced one of my issues earlier, I thought I'd tell you how we solved a similar issue. That issue was about how to generate email receipts upon triggering the subsequent payments of a recurring contribution schedule. Before, when I was creating contributions as completed, no email was being triggered. When I (now) create those contributions as pending, and then use the api method 'completetransaction' then there is a parameter to that method to turn on or off email notifications (by default, it's on).
