### ISSUE TITLE
Payment processor problem without <AmdmntInd>false</AmdmntInd>

### ISSUE THREAD

**Issue by zabinetta** [Project60/org.project60.sepa#391]
Dear Project60,
we had to try around a lot until our client's banking software took our exported xml file.
one of the problems might have been that the required field AmdmntInd was missing.
it should be just before </MndtRltdInf> in  org.project60.sepa/templates/CRM/Sepa/xml/TransactionGroup.tpl, line 62
`<MndtRltdInf>
            <MndtId>{$contribution.reference}</MndtId>
            <DtOfSgntr>{$contribution.validation_date|crmDate:"%Y-%m-%d"}</DtOfSgntr>
           <AmdmntInd>false</AmdmntInd>
</MndtRltdInf>`

with the best regards,
Sabine

**Comment by systopia** [comment]
Thank you Sabine, we'll take care of it. 

Unfortunately we'll cannot simply add the line, because we have to make sure it doesn't cause problems with the banks that people are using with the current format. I know it shouldn't - but I've seen a lot :-) 

If it does cause trouble, we'll add it as an extra format.
