### ISSUE TITLE
Hook civicrm_links declared twice

### ISSUE THREAD

**Issue by rthouvenin** [Project60/org.project60.sepa#437]
The hook `sepa_civicrm_links` is declared twice, with different definitions. This prevents installing the extension from the master branch.

**Comment by systopia** [comment]
Thanks @rthouvenin.

As stated in the https://github.com/Project60/org.project60.sepa/blob/master/README.md the master branch is not suitable for deployment. We would like to change it to the latest release but some people are using it, so it might cause trouble with them since it would be a step back. But I guess we'll to it soon anyway, apparently a lot of people don't read the readme.

**Comment by rthouvenin** [comment]
OK Thanks. 
Yep I saw that but didn't understand that the master branch shouldn't be used at all, so I thought would be useful to mention. I was building a test environment and already new the extension, so I grabbed master without giving much thought about it. 

Anyway, I am happy to stick to 1.2.x :)

**Comment by systopia** [comment]
It's good to know, but ``master`` has some stuff pulled from some other people and I have no idea what's currently going on there, and I don't have the time to look into this right now.

Having said that, it's probably inevitable to change ``master`` to something I that I do have control over :)

**Comment by systopia** [comment]
Current ``master`` should be clean. @rthouvenin Please re-open if problem persists.
