### ISSUE TITLE
Update from 0.1 to 1.2.5 fails

### ISSUE THREAD

**Issue by grince** [Project60/org.project60.sepa#495]
Hi,

I took over a site with CiviCRM and Payment Processors from a former admin. One of my first steps was to (successfully) update the Drupal Website and CiviCRM to their latest respective versions. So, I have CiviCRM-4.6.37.

Then, CiviCRM mentioned that my Extension for SEPA-Payment Processing is outdated and I should update it. I was happy about it and let it do it's work.
But now, CiviCRM doesn't work anymore.
I get a 
"Fatal error: require_once(): Failed opening required 'CRM/Core/Payment/SEPA/DD.php' (include_path='[..]) in /www/htdocs/vocalmus/eva/sites/all/modules/civicrm/Civi/Payment/System.php on line 52"

so, apparently this update didn't work. because where once was a 'SEPA/DD.php', there is now a 'SDD.php'.

so, what can I do now? what am I missing?

**Comment by xurizaemon** [comment]
Rephrasing my advice from chat, in case it was unclear there - this is what I think you should do:

- Move the old `sepa_dd` extension folder (which I think your site has obtained from civicrm-community/sepa_dd repo, but which is now very outdated) to some other location
- Ensure the copy of this repo you have installed is the currently recommended release (from CiviCRM.org or here)
- Check the DB tables `civicrm_extension`, `civicrm_payment_processor_type` - these may contain references to the old `sepa_dd` folder name, but that needs to be updated (or the next autoupdate may break similarly)
- If that still misbehaves: You might need to do something even weirder, like `ln -s org.project360.sepa sepa_dd` so that CiviCRM finds the extension during bootstrap. :nauseated_face: 
- If CiviCRM then chokes on missing files: You might need to create dummy files / classes just to let CiviCRM bootstrap far enough to clear its caches. :mask: 

Unfortunately you've hit multiple gotchas in CiviCRM with this:

- CivICRM loads payment processors very early in bootstrap, and a missing / relocated payment processor can break the site hard.
- CiviCRM autoupdate mechanism doesn't respect existing folder locations, and can "upgrade" an extension by downloading the update to a nearby folder which it then ignores.
- This extension seems to have changed some filenames during its history, which may require CiviCRM caches to be cleared, which may be impossible if it can't bootstrap because of a relocated extension.
- There's no GUI way to correct a badly named extension folder, this requires DB edits.

(this last is just commentary, and may be outdated information, but it's all gotchas I've seen in the past)

**Comment by Detsieber** [comment]
Hi grince,

there is one very hard "hack" to get your civicrm up and running again
(this requires access to your database):

Look at the database table civicrm_payment_processor and set the flag
is_active to "0" for those with class name "Payment_SEPA_DD".

Then, you should be able to start your civicrm again, and get everything
back to work.


Good luck

Detlev


Detlev Sieber
civiservice.de
Rheingaustraße 167, D-65203 Wiesbaden

Tel: +49-611-36056562
Fax: +49-611-36056563
Mobil: +49-170-4007278
Mail: detlev.sieber@t-online.de

Am 02.07.2018 um 13:49 schrieb Chris Burgess:

**Comment by xurizaemon** [comment]
Nice tip @Detsieber!

In case it's not clear - CiviCRM will be trying to load `CRM/Core/Payment/SEPA/DD.php` because it sees that `Payment_Sepa_DD` classname in the DB (plus Civi's class resolving voodoo). So disabling this payment processor will circumvent that error during bootstrap.

Once you get up and running, you'll need to reconfigure each payment page to use the new payment processor classes you enable.

**Comment by tttp** [comment]
Ouch, quite a jump of version @grince! 

I don't recall what civicrm-community was meant to be, but for sepa, you should get everything working and upgrading using the official sepa version

and yes, @Detsieber seems to be the way out of that situation.
X+

**Comment by grince** [comment]
I was able to upgrade after deleting sepa_dd as payment processor, so that went well. in the extensions-directory, it is still called "sepa_dd", but i guess that is less problematic, since info.xml is the new one.
