### ISSUE TITLE
Sepa batch/group get created for sent contributions

### ISSUE THREAD

**Issue by adanielvv** [Project60/org.project60.sepa#507]
A batch was sent with collectiondate set to tomorrow (28), and while closing all contributions were set to Completed.

Clicking on Update recurring creates a new batch, set to the standard collectiondate, which is yesterday (26). It should create a batch which needs to be collected on the 26th, next month.

Settings:
Cycle Day(s) : 26
Only Completed Contributions: yes
Large Groups: yes
Improve payment processor form: yes

**Comment by systopia** [comment]
It sounds like you missed the original collection date (26th). This should be an absolute exception, since it messes up the scheduling - as you observed. You should have received a warning when you did that.

Background: The system will generate the contributions to collect if they're not there already. For this, it uses the collection date. If you change the collection date *and* use the 'only completed' option, the existing contributions aren't found any more - and consequently re-created. Maybe in the future we can improve the link between contribution and mandate, so this scenario is covered (#501 might be a good starting point), but for the time being you have to avoid missing the submission date. Especially with 'only completed' enabled.

In your scenario, I would delete the group and the contributions, and not use the update again for a couple of days. As soon as it's past the grace period, the bad group should not be created any more.

**Comment by ErikHommel** [comment]
I have a slightly similar issue where some data got migrated wrongly. We have solved this by setting the contributions to "Completed" but they still get selected by this query in the updateRcur function:

````php
 $sql_query = "
        SELECT
          contribution.contribution_recur_id AS contribution_recur_id, 
          contribution.id                    AS contribution_id
        FROM civicrm_contribution contribution 
        LEFT JOIN civicrm_sdd_contribution_txgroup ctxg ON ctxg.contribution_id = contribution.id 
        LEFT JOIN civicrm_sdd_txgroup               txg ON txg.id = ctxg.txgroup_id 
        WHERE contribution.contribution_recur_id IN ({$rcontrib_id_strings})
          AND DATE(contribution.receive_date) = DATE('{$collection_date}')
          AND (txg.type IS NULL OR txg.type IN ('RCUR', 'FRST'))
          AND contribution.payment_instrument_id = {$payment_instrument_id};";
````
Should this not include a check on contribution_status_id so completed contributions are not picked up? If we do that just like that then the contributions are recreated, which we do not want either. So should completed contributions not be kept out of the considerations overall?

**Comment by ErikHommel** [comment]
Or perhaps a few lines have to be added to the syncGroups function just before:
````php

      // the remaining must be added
      foreach ($entity_ids as $entity_id) {
        CRM_Core_DAO::executeQuery("INSERT INTO civicrm_sdd_contribution_txgroup (txgroup_id, contribution_id) VALUES ($group_id, $entity_id);");
      }

````
where all completed contributions are removed?

**Comment by bjendres** [comment]
I still don't get how you got into that situation, but adding a check for contribution status wouldn't help: then it wouldn't find the completed one, generate a new one, and collect that (again).

I think this contribution shouldn't be set to completed before the group is closed/received.

**Comment by bjendres** [comment]
@adanielvv does this still happen? We have recently adjusted the way that the deferral works...

**Comment by ErikHommel** [comment]
@bjendres we got the situation, as stated, because data was migrated with an error, not because a contribution was set to completed manually :-) It was never sent with a group, it was sent in the 'old'  system. Never mind, if it does and should not happen in any other situation then it is a one-time problem.

**Comment by bjendres** [comment]
Ok, thanks, @ErikHommel. I'll close the ticket, and will re-open if obeserved "in the wild"
