### ISSUE TITLE
payment processor does not work in drupal webform

### ISSUE THREAD

**Issue by lbl-knts** [Project60/org.project60.sepa#602]
With CiviCRM 5.29 and CiviSepa 1.4, used the extension for processing contributions. Using the extension in civicrm contribution pages, everything went well. 

For some reasons it might be good to use drupal webform for online contributions. Whith that, i get an error 

`Notice: Undefined property: CRM_Core_Payment_SDD::$_paymentForm in CRM_Core_Payment->getForm() (line 555 von [...]/sites/all/modules/civicrm/CRM/Core/Payment.php).`

Looking to CiviCRM, the contribution is recorded as contribution, but without creating a Sepa mandate. It seems to "fall back" to a different payment processor with the value of 1, so it might have problems to select the correct payment processor while giving the record from webform to civicrm. 
Besides, with the `SEPA DD` processor a transaction id in correct format was created (but still with the wrong payment processor), with the `SEPA DD (new)` this information is missing too. 

Anyone who has experienced that, too?

**Comment by bjendres** [comment]
The SEPA payment processors aren't really up to date, since we (maintainers) are rarely using it. Also, in the past, fixes/adjustments that worked for one user didn't work for another and vice versa. To address this problem, we are currently in the process of refactoring the payment processors into a separate extension, and will roll this out with the upcoming CiviSEPA ``1.5`` release. This way everyone can have different versions of the payment processor, without compromising the CiviSEPA core.

That being said, you should maybe move this issue to https://github.com/Project60/org.project60.sepapp.
