### ISSUE TITLE
payment is created with OOFF contribution, but not with RECUR contribution

### ISSUE THREAD

**Issue by lbl-knts** [Project60/org.project60.sepa#611]
The extension seems to differ if it's a one-time or recurring contribution. 
Use case: a filled public contribution page with one-time contributions >creates a payment entry< within the contribution. 
While having recurring contributions, the extension >does not create any payment< entry. 

Any hints for what this differ?

CiviSepa 1.4 and 1.5, CiviCRM 5.36, WP

**Comment by bjendres** [comment]
Hi @lbl-knts. There's some stuff to unpick here.

> The extension seems to differ if it's a one-time or recurring contribution.
> Use case: a filled public contribution page with one-time contributions >creates a payment entry< within the contribution.
> While having recurring contributions, the extension >does not create any payment< entry.

Yes, that's by design. Recurring contribution create a recurring mandate, which only generates a contribution when the transaction groups are generated. One-Off donations will only be collected once, so the contribution is created along with the mandate.

> Any hints for what this differ?

Yes, you should maybe have a look a the documentation here: https://docs.civicrm.org/civisepa/en/latest/

Furthermore: with the current version ``1.5`` the payment processor code has been removed from CiviSEPA (this project) and moved to the SEPAPP extension here: https://github.com/Project60/org.project60.sepapp.

So if you want to follow up on the specific behaviour of the the CiviSEPA payemnt processors, please open a ticket there.
