### ISSUE TITLE
Searching contacts with bank account

### ISSUE THREAD

**Issue by eptbertram** [Project60/org.project60.sepa#636]
I thought this would be easy, but I can't build a search for all contacts with bank accounts in my CRM. I tried search-generator and search-kit, but there is no bank account / bank / IBAN entity nor field. 

CiviSEPA does a lookup for bank accounts (e.g. when creating a new mandate). Why can't I do this within a contact search? btw: searching SEPA-mandates is working fine, but my aim is to search contacts with bank accounts to ask them to take part in SEPA. 

Does anyone have an answer for my question?

**Comment by bjendres** [comment]
I'm not quite sure I understand what you want to do, but wouldn't the CiviSEPA Reports help?

**Comment by eptbertram** [comment]
Hej @bjendres thanx for your fast reply. No, CiviSEPA won't help here. 

I have ~90 bank accounts imported from CiviBanking in my CRM, but only 10 SEPA-mandates in this CRM. Aim: search these missing 80 contacts and ask them for a SEPA-mandate.

**Comment by jensschuppe** [comment]
There is a bank account search in CiviBanking (`civicrm/banking/search`) which you can feed a `%` wildcard as part of the account number to find all bank accounts recorded by CiviBanking. Unfortunately, this is not yet included in a contact search.

Since bank accounts and bank account references are CiviCRM entities, they could be made available through APIv4 which would allow for configuring searches using SearchKit. This will have to be done in the CiviBanking extension though, and not within CiviSEPA.

**Comment by bjendres** [comment]
Can we close here, @eptbertram?

**Comment by eptbertram** [comment]
Yes, thank you both!
