### ISSUE TITLE
Update l10n

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#666]
Some recent developments have added more strings to the CiviSEPA extension, so we should adjust the localisations before releasing ``1.9.0``.

**Comment by bjendres** [comment]
@masetto Would you want to add an Italian ``mo`` file?

**Comment by masetto** [comment]
Yes, I'd like that. Please confirm that these are the steps:
1. Translate in italian using [Transifex](https://www.transifex.com/civicrm/civicrm_extensions/sepa/)
2. Download sepa.po from Transifex and create .mo
3. Create a PR to add "l10n/it_IT" files.

**Comment by bjendres** [comment]
Hm, I'm not even sure the strings on Transifex are up to date. I usually just translate here in the repository...

**Comment by francescbassas** [comment]
Hi, only in case it helps, recently the translation channel has been talking about this new extension https://lab.civicrm.org/extensions/uplang which I think makes it easier to manage and maintain translations for extensions like this.

**Comment by mlutfy** [comment]
It would be nice to have it in Transifex, so that non-devs can translate, and have CiviCRM update translations automatically (uplang/l10nupdate).

For that to happen, you just need to request a review, so that the extension is available "in-app" (aka "reviewed extension" badge on civicrm.org/extensions).

To ask for a review, a maintainer can open an issue here: https://lab.civicrm.org/extensions/extension-review-requests/-/issues/ (you can look at other requests, it's really just posting a link to the extension's page in the directory).

Once reviewed, the rest is automated (updating Transifex, generating mo files, etc).
