### ISSUE TITLE
How to manage a bank chargeback

### ISSUE THREAD

**Issue by francescbassas** [Project60/org.project60.sepa#709]
I'm trying to figure how to manage bank chargebacks.

In first place I edit the contribution from completed to chargeback.
Aafter that it will depend on the case but it is likely that it will be necessary to change the bank account and transfer the charge again. I don't see how it should be done. The date of the recurring contribution is fixed for the next period and it is not possible to change it, right?

**Comment by bjendres** [comment]
> In first place I edit the contribution from completed to chargeback. Aafter that it will depend on the case but it is likely that it will be necessary to change the bank account and transfer the charge again. I don't see how it should be done. 

We usually do this in a mostly automated way:
1. Use CiviBanking with the SepaMandateMatcher to process the file containing the chargebacks. This will automatically adjust the status of the individual SEPA contributions, and can even put the difference to the original amount into a custom field for chargeback fees and the chargeback reason. Setting up CiviBanking is a bit of work, though.
2. Then use CiviSEPA's "retry collection" feature to (manually) select the contributions to retry collecting - usually based on date, contribution status, and chargeback reason.

> The date of the recurring contribution is fixed for the next period and it is not possible to change it, right?

Beyond the the ``RETRY`` groups, yes, otherwise the group scheduler would adjust the collection date, and possibly collect duplicates. #576 would solve that, but there's currently not interest/funding for it.

**Comment by francescbassas** [comment]
Thanks for the indications @bjendres I'll try retry collection options. Perhaps this indications could be added in the [How to Guide Docs section](https://docs.civicrm.org/civisepa/en/latest/how-to)?

**Comment by bjendres** [comment]
> Perhaps this indications could be added in the [How to Guide Docs section](https://docs.civicrm.org/civisepa/en/latest/how-to)?

I agree. If you have the time to create a draft, PRs are very much appreciated!

**Comment by francescbassas** [comment]
@bjendres I think the PR in the documentation it's not published https://github.com/Project60/org.project60.sepa/pull/711

I tried to force re-publication of the CiviSEPA docs but something seems broken https://docs.civicrm.org/admin/publish/civisepa. Any idea?

**Comment by francescbassas** [comment]
Publication issue it's now solved. "How to manage a bank chargeback" is now in the documentation.

**Comment by bjendres** [comment]
> Publication issue it's now solved. "How to manage a bank chargeback" is now in the documentation.

Great, thanks!
