### ISSUE TITLE
Error, undefined variable in civix file

### ISSUE THREAD

**Issue by colemanw** [Project60/org.project60.sepa#712]
@jaapjansma added this line to the civix file manually: https://github.com/Project60/org.project60.sepa/blob/1363cd27d96edd51e58777ac5083f3f6d3720d01/sepa.civix.php#L97

However I notice that the variable `$extDir` is undefined. This will cause an error.

I'm not sure why it was updated manually, but as this is an autogenerated file, I recommend regenerating it using the latest version of `civix`.

**Comment by bjendres** [comment]
> I'm not sure why it was updated manually, but as this is an autogenerated file, I recommend regenerating it using the latest version

That, unfortunately and needlessly, breaks compatibility with older CiviCRM versions. I believe we have discussed that before.

**Comment by jaapjansma** [comment]
@colemanw we experience issues with Civix and autogenerating files. Especially because a lot of extensions are running in different versions of CiviCRM. So I, and others, tend to avoid Civix and do our changes manually. 
This might be good to discuss in Hamburg (are you be there?).

So that is why that change is done manually. And you are right I removed a needed variable. 

And I fixed this right now

**Comment by colemanw** [comment]
> @bjendres That, unfortunately and needlessly, breaks compatibility with older CiviCRM versions. I believe we have discussed that before.

I know @totten goes to great efforts in civix to ensure that it *doesn't* break b/c. So if there's a breakage I suggest filing an issue with https://github.com/totten/civix so that can be fixed.

> @jaapjansma This might be good to discuss in Hamburg (are you be there?).

Tim will be there :)
